# /etc/skel/.bashrc
#
# This file is sourced by all *interactive* bash shells on startup,
# including some apparently interactive shells such as scp and rcp
# that can't tolerate any output.  So make sure this doesn't display
# anything or bad things will happen !


# Test for an interactive shell.  There is no need to set anything
# past this point for scp and rcp, and it's important to refrain from
# outputting anything in those cases.
if [[ $- != *i* ]] ; then
	# Shell is non-interactive.  Be done now!
	return
fi


# Put your fun stuff here.

#alias gettext_printf="printf"
alias git-last="git log -p --"
alias gentooradio="mpv http://radio.sussywebsite.xyz/listen/mpd.ogg"
alias emergeall="rdo emerge --deep --update --newuse --verbose --ask --keep-going --autounmask-write --with-bdeps=y @smart-live-rebuild"
alias emergeallk="rdo emerge --deep --update --newuse --verbose --ask --keep-going --autounmask-write --with-bdeps=y -X sys-kernel/gentoo-sources @smart-live-rebuild"
alias startx="xinit -- vt$(tty | sed -e 's|/dev/tty||')"
alias github="oathtool -b --totp SGIGCL766H6LOBPU"
#alias startx="startx -- vt$(tty | sed -e 's|/dev/tty||')"
#alias startx="startx -- vt$(tty | sed -e 's|/dev/pts/||')"
#alias kirc-gentoo="cd /home/stefan/HDD1/irc && /usr/local/bin/kirc -c gentoo -n stefan11111"
alias kirc-gentoo="/usr/bin/kirc -c gentoo -n stefan11111 -o /home/stefan/HDD1/logs/gentoo-log.txt"
alias kirc="kirc -s irc.rizon.net -c subsplease -n hentai_god -d -D /home/stefan/HDD1/irc"
alias doas="rdo"
alias mpv="mpv --fullscreen"
#alias leafpad="l3afpad"
#alias nano="nano -l"
alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
#alias ro="setxkbmap ro std"
#alias en="setxkbmap ro"
flashfetch
