# /etc/skel/.bashrc
#
# This file is sourced by all *interactive* bash shells on startup,
# including some apparently interactive shells such as scp and rcp
# that can't tolerate any output.  So make sure this doesn't display
# anything or bad things will happen !


# Test for an interactive shell.  There is no need to set anything
# past this point for scp and rcp, and it's important to refrain from
# outputting anything in those cases.
if [[ $- != *i* ]] ; then
	# Shell is non-interactive.  Be done now!
	return
fi


# Put your fun stuff here.

alias emergeall="rdo emerge --deep --update --newuse --verbose --ask --keep-going --autounmask-write --with-bdeps=y"
alias startx="startx -- vt$(tty | sed -e 's|/dev/tty||')"
alias kirc="cd /home/stefan/HDD1/irc && kirc -s irc.rizon.net -c subsplease -n hentai_god"
alias doas="rdo"
alias mpv="mpv --fullscreen"
#alias nano="nano -l"
flashfetch
#neofetch
