#!/bin/sh

slstatus &
xcompmgr &
/usr/bin/feh --bg-fill '/home/stefan/images/wallpapers/2.jpg' &
xset -dpms &
xset s off &
rdo ntpd &
qbittorrent-nox &
rdo curl https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts > /etc/hosts &
rdo mount -a &
exec dwm
