# These settings were set by the catalyst build script that automatically
# built this stage.
# Please consult /usr/share/portage/config/make.conf.example for a more
# detailed example.
COMMON_FLAGS="-O2 -pipe -march=native"
MAKEOPTS="-j4"
CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"
NTHREADS="4"
ACCEPT_LICENSE="*"
ACCEPT_KEYWORDS="~amd64"
USE="-clang -pipewire -gnutls -selinux -accessibility -Xaw3d -audit -udisks -policykit -plasma -radius -emacs -encode -fastcgi
     -gnome-keyring -gnuplot -gphoto2 -gsl -gstreamer -latex -ggi -aqua -coreaudio -emboss -smartacard -ibm -neon -mms -kde -lvm
     -systemd -gnome -ios -ipod -clamav -quicktime -bluetooth -wifi -wayland -xemacs -xface -xinerama -xscreensaver -cups
     -gtk -gtk2 -gtk3 -qt -qt4 -qt5 -qt6 -introspection -vala
     gimp git cjk verify-sig man alsa realtime pulseaudio X nvidia config samba unicode upnp usb harfbuzz
     lto pgo libressl elogind abi_x86_32"
INPUT_DEVICES="libinput synaptics"
VIDEO_CARDS="nvidia"
# NOTE: This stage was built with the bindist Use flag enabled
PORTDIR="/var/db/repos/gentoo"
DISTDIR="/var/cache/distfiles"
PKGDIR="/var/cache/binpkgs"

# This sets the language of build output to English.
# Please keep this setting intact when reporting bugs.
LC_MESSAGES=C

GENTOO_MIRRORS="http://ftp.romnet.org/gentoo/ http://mirrors.xservers.ro/gentoo/"
CURL_SSL="libressl"
GRUB_PLATFORMS="efi-64"
#source /var/lib/layman/make.conf
#source /etc/portage/make.conf.lto
