[libressl]
priority = 50
location = /var/lib/layman/libressl
layman-type = git
auto-sync = No

[steam-overlay]
priority = 50
location = /var/lib/layman/steam-overlay
layman-type = git
auto-sync = No

[vifino-overlay]
priority = 50
location = /var/lib/layman/vifino-overlay
layman-type = git
auto-sync = No

